name: minipress_app
environment:
  sdk: "^3.11.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  # HTTP
  dio: ^5.7.0
  # State management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5
  # Navigation
  go_router: ^14.0.0
  # Modèles de données
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_markdown: ^0.7.3
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Génération de code
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3

flutter:
  uses-material-design: true
